# Generated by Django 6.0.1 on 2026-02-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
