# Generated by Django 6.0.1 on 2026-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='unblocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
