# Generated by Django 6.0.1 on 2026-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_generallog_blockedip_status_alter_blockedip_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='destination_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
