# Generated by Django 6.0.1 on 2026-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_threat_destination_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=150),
        ),
    ]
